const prefixList = [
  { prefix_eff: 1, title: "강인한" },
  { prefix_eff: 2, title: "근성있는" },
  { prefix_eff: 3, title: "맹렬한" },
  { prefix_eff: 4, title: "힘있는" },
  { prefix_eff: 5, title: "튼튼한" },
  { prefix_eff: 6, title: "견고한" },
  { prefix_eff: 8, title: "재빠른" },
  { prefix_eff: 9, title: "치명적인" },
  { prefix_eff: 10, title: "잔혹한" },
  { prefix_eff: 11, title: "저항하는" },
  { prefix_eff: 12, title: "정교한" },
];
const setList = [
  { set_id: 1, title: "활력" },
  { set_id: 2, title: "수호" },
  { set_id: 3, title: "신속" },
  { set_id: 4, title: "칼날" },
  { set_id: 5, title: "격노" },
  { set_id: 6, title: "집중" },
  { set_id: 7, title: "인내" },
  { set_id: 8, title: "맹공" },
  { set_id: 10, title: "절망" },
  { set_id: 11, title: "흡혈" },
  { set_id: 13, title: "폭주" },
  { set_id: 14, title: "응보" },
  { set_id: 15, title: "의지" },
  { set_id: 16, title: "보호" },
  { set_id: 17, title: "반격" },
  { set_id: 18, title: "파괴" },
  { set_id: 19, title: "투지" },
  { set_id: 20, title: "결의" },
  { set_id: 21, title: "고양" },
  { set_id: 22, title: "명중" },
  { set_id: 23, title: "근성" },
];
const optionList = [
  { id: 1, title: "체력+" },
  { id: 2, title: "체력+" },
  { id: 3, title: "공격력+" },
  { id: 4, title: "공격력+" },
  { id: 5, title: "방어력+" },
  { id: 6, title: "방어력+" },
  { id: 8, title: "공격속도+" },
  { id: 9, title: "치명피해+" },
  { id: 10, title: "치명확률+" },
  { id: 11, title: "효과저항+" },
  { id: 12, title: "효과적중+" },
];

export { prefixList, setList, optionList };
